### ISSUE TITLE
widget importer button not working

### ISSUE THREAD

**Issue by carlilelance** [voceconnect/widget-data#25]
When I click on the "select a file" button on widget import, nothing happens. My logs say this:

 AH01630: client denied by server configuration: /var/www/html/wordpress/wp-content/plugins/widget-settings-importexport/widget-data.js, referer: http://<www.blog.com>/wordpress/wp-admin/tools.php?page=widget-settings-import

Any assistance is much appreciated. Using Centos 7.

**Comment by kevinlangleyjr** [comment]
@carlilelance - It looks like on the WordPress.org SVN repo the JS, PHP, and the readme.txt files were all marked as executable.

I've since changed this and released version 1.5.2.

Let me know if you run into any other issues.

Thanks!

**Comment by carlilelance** [comment]
I'm still running into the same issue, but thanks for your efforts. I'm wondering if the plugin is running as a different user than apache.

**Comment by kevinlangleyjr** [comment]
Are you downloading the plugin from WP.org or GitHub?
